name: RespawnNpc
main: de.mahagst.risingworld.respawnnpc.RespawnNpcPlugin
version: 1.0.0
api: 0.9.3
author: mahagst
description: Respawn NPCs after death
website: https://api.github.com/repos/HaggerShose/rw-respawn-npc/releases/latest
