package de.mahagst.risingworld.respawnnpc;

/**
 * One registered respawn NPC. nextRespawn null = idle (alive / no pending timer).
 * Spawn pose is register-time; snapshot fields change only on register / update.
 * yaw is degrees (horizontal facing only).
 */
record RespawnNpc(
		long respawnId,
		long currentNpcId,
		short typeId,
		int variant,
		String typeName,
		float posX,
		float posY,
		float posZ,
		float yaw,
		int intervalSeconds,
		Long nextRespawn,
		long createdAt,
		String name,
		int health,
		int hunger,
		int thirst,
		float taming,
		int age,
		String behaviour,
		boolean behaviourOverridden,
		String attackReaction,
		boolean attackReactionOverridden,
		int groupId,
		boolean locked,
		boolean npcStatic,
		boolean invincible,
		boolean invisible,
		boolean interactable,
		boolean colliderEnabled,
		boolean footstepSoundEnabled,
		boolean idleSoundEnabled,
		boolean alertSoundEnabled,
		Short equippedTypeId,
		Integer equippedVariant,
		Integer equippedStatus,
		Float equippedValue,
		Integer equippedDurability,
		String equippedModifier,
		byte[] clothes,
		String skinGender,
		Byte skinVariation,
		Integer skinColor,
		Integer eyeColor,
		Integer hairColor,
		Byte hairstyle,
		Byte beard,
		Short secondaryTypeId,
		Integer secondaryVariant,
		Integer secondaryStatus,
		Float secondaryValue,
		Integer secondaryDurability,
		String secondaryModifier,
		boolean pregnant) {
}
